# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
   corsListener:
        class: AppBundle\EventListener\CorstEventListerner
        arguments: ['%cors%','@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 9999999 }
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 999999 }
    