AppBundle\Entity\Interessado:
    type: entity
    table: interessado
    indexes:
        convite_id:
            columns:
                - convite_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        endereco:
            type: string
            nullable: false
            length: 500
            options:
                fixed: false
        telefone:
            type: string
            nullable: false
            length: 14
            options:
                fixed: false
        dataNascimento:
            type: datetime
            nullable: false
            column: data_nascimento
    manyToOne:
        convite:
            targetEntity: Convite
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                convite_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
